# Generated by Django 6.0.3 on 2026-04-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('shopping', 'Shopping'), ('bill', 'Bill'), ('health', 'Health'), ('other', 'Other')], max_length=30),
        ),
    ]
